AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'Gemfile'
  
  Style/FrozenStringLiteralComment:
    Enable: false